name: cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.19.0
  commander_ui: ^1.8.0
  dart_style: ^2.3.7
  mineral:
    path: ../core
  path: ^1.9.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
